---
# ============================================================
# OVERLAY STAGING — Kustomization
# Déployé automatiquement à chaque merge sur main
# ============================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

bases:
  - ../../base

resources:
  - namespace.yaml
  - resource-quota.yaml
  - secrets.yaml
  - ingress.yaml
  - configmap.yaml

patchesStrategicMerge:
  - patches/replicas.yaml
  - patches/resources.yaml
  - patches/storage.yaml

images:
  - name: ghcr.io/bhaon/studi-bloc3-mmotors-frontend
    newTag: staging-latest
  - name: ghcr.io/bhaon/studi-bloc3-mmotors-backend
    newTag: staging-latest

commonLabels:
  environment: staging

commonAnnotations:
  managed-by: kustomize
  environment: staging
